# Generated by Django 4.0.5 on 2022-06-11 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_project_repo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Project_url',
            new_name='project_url',
        ),
    ]
